DROP TABLE IF EXISTS `cadastro`;
CREATE TABLE IF NOT EXISTS `cadastro` (
  `codigo` int(11) NOT NULL AUTO_INCREMENT,
  `negociacao` int(11) NOT NULL,
  `tipo` varchar(10) NOT NULL,
  `endereco` varchar(20) NOT NULL,
  `bairro` varchar(20) NOT NULL,
  `cidade` varchar(20) NOT NULL,
  `regiao` varchar(20) NOT NULL,
  `salas` int(11) NOT NULL,
  `quartos` int(11) NOT NULL,
  `suites` int(11) NOT NULL,
  `banheiro` int(11) NOT NULL,
  `garagem` int(11) NOT NULL,
  `descricao` text NOT NULL,
  `area_construida` float NOT NULL,
  `area_total` float NOT NULL,
  `area_comum` float NOT NULL,
  `area_terreno` float NOT NULL,
  `destaque` tinyint(1) NOT NULL,
  `lancamento` tinyint(1) NOT NULL,
  `disponivel` tinyint(1) NOT NULL,
  `mostrar_site` tinyint(1) NOT NULL,
  `titulo` varchar(10) NOT NULL,
  `condominio_fechado` tinyint(1) NOT NULL,
  `despensa` tinyint(1) NOT NULL,
  `lavabo` tinyint(1) NOT NULL,
  `piscina` tinyint(1) NOT NULL,
  `sauna` tinyint(1) NOT NULL,
  `area_servico` tinyint(1) NOT NULL,
  `lavanderia` tinyint(1) NOT NULL,
  `piso_frio` tinyint(1) NOT NULL,
  `armario_embutido` tinyint(1) NOT NULL,
  `churrasqueira` tinyint(1) NOT NULL,
  `escritorio` tinyint(1) NOT NULL,
  `sacada` tinyint(1) NOT NULL,
  `varanda` tinyint(1) NOT NULL,
  `cozinha_planejada` tinyint(1) NOT NULL,
  `salao_festa` tinyint(1) NOT NULL,
  `portaria` tinyint(1) NOT NULL,
  `imagem` blob NOT NULL  ,
  PRIMARY KEY (`codigo`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
